pdf(width=14)
orilocale <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "C")
par(mar=c(3.1,4.1,2.1,4.1), las = 1)
plot.zoo(Thetasum[,"K7ÉPth"], lwd=2, xaxs = "i", ylab = "Theta [%]",
         ylim = c(0,20), yaxs ="i", type="n", xaxt = "n", xlab = "")
grid(nx = NA, ny = NULL)
tick.month <- seq.Date(as.Date("2018-07-01"), as.Date("2021-04-01"), by = "1 month")
tick.year <- seq.Date(as.Date("2019-01-01"), as.Date("2021-01-01"), by = "1 year")
axis(1, at = tick.month, tck = 1,
     col = "lightgray", lty = "dotted", lab = F)
axis(1, at = tick.year, tck = 1,
     col = "lightgray", lab = F, lwd = 2)
axis(1, at = tick.month[-1], lab=F)
axis.Date(1, at = tick.month + 15, tcl = 0, format = "%b", cex.axis = 0.75)
yeartext <- c(tick.year - c(91,183,183), tick.year[length(tick.year)] + 50)
text(x = yeartext, y = rep(0.8, length(tick.year)), labels = format(yeartext, format = "%Y"), cex = 2, col = "lightgray")
lines(as.zoo(Thetasum[,"K7ÉPth"]), lwd = 2)
lines(as.zoo(Thetasum[,"K7ÉPth"] - 2 * Thetasum[,"K7ÉPsd"]), lty="dotted")
lines(as.zoo(Thetasum[,"K7ÉPth"] + 2 * Thetasum[,"K7ÉPsd"]), lty="dotted")
lines(as.zoo(Thetasum[,"K35Fth"]), lwd = 2, col = 2)
lines(as.zoo(Thetasum[,"K35Fth"] - 2 * Thetasum[,"K35Fsd"]), lty="dotted", col = 2)
lines(as.zoo(Thetasum[,"K35Fth"] + 2 * Thetasum[,"K35Fsd"]), lty="dotted", col = 2)
lines(as.zoo(Thetasum[,"K12Eth"]), lwd = 2, col = 3)
lines(as.zoo(Thetasum[,"K12Eth"] - 2 * Thetasum[,"K12Esd"]), lty="dotted", col = 3)
lines(as.zoo(Thetasum[,"K12Eth"] + 2 * Thetasum[,"K12Esd"]), lty="dotted", col = 3)
par(new = TRUE)
plot.zoo(Thetasum[,"K7ÉPth"], lwd=2, xaxs = "i",
         ylim = c(-200,0), yaxs ="i", type="n", axes = FALSE, xlab = "",
         ylab = "")
lines(as.zoo(All.xts$Prec * -1), type = "h", col = "blue", lend = 1, lwd = 4)
axis(4, at=c(0,-50,-100), lab = c(0,50,100))
mtext("Precipitation [mm]", side = 4, line = 3, at = -25, las = 0)
Sys.setlocale("LC_TIME", orilocale)
legend(as.Date("2018-07-28"), -65, legend = c("Grassland", "Black locust", "Black pine", "Precipitation"), col = c(1:3, "blue"), lty=1, lwd = c(2, 2, 2, 3) , bg = "white")
