par(las = 1)
plot.zoo(Thetasum[,"K7ÉPth"], lwd=2, xaxs = "i", ylab = "Theta [%]", ylim = c(0,20), type="n", xaxt = "n", xlab = "")
grid(nx = NA, ny = NULL)
tick.month <- seq.Date(as.Date("2018-08-01"), as.Date("2021-04-01"), by = "1 month")
axis(1, at = tick.month, tck = 1,
     col = "lightgray", lty = "dotted", lab = F)
axis(1, at = tick.month, lab=F)
axis.Date(1, at = tick.month + 15, tcl = 0, format = "%m")
lines(as.zoo(Thetasum[,"K7ÉPth"]), lwd = 2)
lines(as.zoo(Thetasum[,"K7ÉPth"] - Thetasum[,"K7ÉPsd"]), lty="dotted")
lines(as.zoo(Thetasum[,"K7ÉPth"] + Thetasum[,"K7ÉPsd"]), lty="dotted")
lines(as.zoo(Thetasum[,"K35Fth"]), lwd = 2, col = 2)
lines(as.zoo(Thetasum[,"K35Fth"] - Thetasum[,"K35Fsd"]), lty="dotted", col = 2)
lines(as.zoo(Thetasum[,"K35Fth"] + Thetasum[,"K35Fsd"]), lty="dotted", col = 2)
lines(as.zoo(Thetasum[,"K12Eth"]), lwd = 2, col = 3)
lines(as.zoo(Thetasum[,"K12Eth"] - Thetasum[,"K12Esd"]), lty="dotted", col = 3)
lines(as.zoo(Thetasum[,"K12Eth"] + Thetasum[,"K12Esd"]), lty="dotted", col = 3)

